# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-

name: dwarffortress
version: 0.47.03
summary: Dwarf Fortress world simulator. Forked from 'https://github.com/mikix/df'.
description: |
  Dwarf Fortress is a single-player fantasy game by Bay 12 Games. You can control a dwarven outpost or an adventurer in a randomly generated, persistent world.

  This is an unofficial snap, which redistributes the original binaries without modification. This version is forked from 'https://github.com/mikix/df'.

  Upstream: http://www.bay12games.com/dwarves/
confinement: strict
grade: stable
architectures: [amd64]

parts:
  tarball:
    plugin: dump
    source: http://www.bay12games.com/dwarves/df_47_03_linux.tar.bz2
    source-checksum: sha512/a7122fb1f5433200f43344f7f905494184ba916d0316cd0bfde1f2d4f11685ec2e0bad0276b169ca34b4fb0774d62e6d1e03060c2d6ef79140ced62cba1fac95
    override-build: |
      chmod a+x df
      find . -type d -exec chmod a+rx {} +
      snapcraftctl build
    prime:
      - -g_src
      - -libs/libstdc++.so.6
  desktop-gtk2:
    after: []
  deps:
    plugin: nil
    stage-packages:
      - freeglut3
      - libglu1-mesa
      - libopenal1
      - libsdl-image1.2
      - libsdl-ttf2.0-0
  overlay:
    plugin: dump
    source: overlay

apps:
  dwarffortress:
    command: desktop-launch $SNAP/wrapper.sh
    plugs: [opengl, pulseaudio, x11, unity7]
